---
- name: install core packages for virtual machines
  hosts: all
  become: yes
  tasks:
  - name: install packages
    apt:
      name:
        - curl
        - unzip
        - nfs-common
        - qemu-guest-agent
      update_cache: yes
  - name: start guest qemu-guest-agent
    service:
      name: qemu-guest-agent
      state: started
      enabled: yes
